variable "controller_type" {}
variable "controller_image" {}
variable "controller_size" {}
variable "controller_count" {}
variable "worker_type" {}
variable "worker_image" {}
variable "worker_size" {}
variable "worker_count" {}
variable "vpc" {}
variable "subnet" {}
variable "region" {}
variable "zone_map" {}
variable "env" {}
